---
abstract: 'eWAY RapidAPI V3'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-eWAY-RapidAPI
requires:
  JSON: 0
  Moo: 0
  MooX::Types::MooseLike: 0
  WWW::Mechanize: 0
  XML::Simple: 0
resources:
  repository: git://github.com/fayland/p5-Business-eWAY-RapidAPI.git
version: 0.03
